version: '3.3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
#    network_mode: host
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
      - '0.0.0.0:67:67/udp'
      - '0.0.0.0:8053:80/tcp'
    environment:
      ServerIP: ${HOST_IP}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.${MAIN_DOMAIN}:8053
      VIRTUAL_PORT: 80
    volumes:
      - ./pihole:/etc/pihole/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    extra_hosts:
      - 'pihole.${MAIN_DOMAIN}:${HOST_IP}'

  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:latest
    network_mode: host
    ports:
      - ${HA_PORT}:${HA_PORT}
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    restart: always
    extra_hosts:
      - 'ha.${MAIN_DOMAIN}:${HOST_IP}'

