---
homeassistant:
  auth_providers:
    - type: homeassistant
#    - type: legacy_api_password
#      api_password: !secret http_password
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 144
  unit_system: metric
  time_zone: Europe/Minsk
  # Customization file
  customize: !include deps/homeassistant/customize.yaml
  customize_glob: !include deps/homeassistant/custom_ui.yaml

zone:
  - name: !secret evgeny_work_name
    latitude: !secret evgeny_work_latitude
    longitude: !secret evgeny_work_longitude

  - name: !secret jane_work_name
    latitude: !secret jane_work_latitude
    longitude: !secret jane_work_longitude

  - name: !secret home_name
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:account-multiple

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_gateway_mac
      key: !secret xiaomi_gateway_key
      host: !secret xiaomi_gateway_host

weather:
  - platform: darksky
    api_key: !secret weather_dark_sky_api_key

# google_assistant:
#  project_id: !secret google_assistant_project_id
#  client_id: !secret google_assistant_client_id
#  access_token: !secret google_assistant_access_token
#  api_key: !secret google_assistant_api_key

#DEPRECATED
#googlehome:
#  devices:
#    - host: !secret google_home_mini_kitchen_host
#    - host: !secret google_home_mini_bathroom_host

#customizer:
#  custom_ui: local
#  hide_attributes:
#    - node_id
#    - value_index

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

logger:
  logs:
    homeassistant.components.dialogflow: debug

influxdb:
  host: 127.0.0.1
  port: 8087
  database: !secret influx_db_name
  username: !secret influx_db_user
  password: !secret influx_db_password
  ssl: false
  verify_ssl: false
  max_retries: 3
  default_measurement: state
  tags:
    instance: prod
    source: hass

pi_hole:
  host: !secret pi_hole_http_host
  api_key: !secret pi_hole_api_key
  name: Pi-hole

# Text to speech
tts:
  - platform: google_translate
# Track router
upnp:
  local_ip: !secret hass_local_ip
# Enable dialogflow integration
dialogflow:
# Enables configuration UI
config:
# Checks for available updates
updater:
# View all events in a logbook
logbook:
# Enables a map showing the location of tracked devices
map:
# Track the sun
sun:
# Custom component for handling complex intents
# custom_components\intent_handler\intent_handler.py
intent_handler:
# Shopping list
shopping_list:
# Configuration input component
input_number: !include deps/input_number.yaml
# Configuration intent component
intent_script: !include deps/intent_script.yaml
# Configuration for media_player component
media_player: !include deps/media_player.yaml
media_extractor:
# Configuration for light component
light: !include deps/light.yaml
# Configuration for plants
plant: !include deps/plants.yaml
# Configuration for web interface
http: !include deps/http.yaml
# Enables support for tracking state changes over time
history: !include deps/history.yaml
# Enables support for tracking state changes over time
recorder: !include deps/recorder.yaml
# Custom sensor configurations
sensor: !include_dir_merge_list deps/sensors/
# Switch configurations
switch: !include deps/switch.yaml
# Fans configurations
fan: !include deps/fans.yaml
# Discover some devices automatically
discovery: !include deps/discovery.yaml
# Notifications (html5/etc)
notify: !include deps/notify.yaml
# MQTT private server config
mqtt: !include deps/mqtt.yaml
# Groups config
group: !include_dir_merge_named groups/
# Home automation
automation: !include_dir_merge_list automations/
# Custom scripts
script: !include deps/scripts.yaml
# Sidebar panels iframe
panel_iframe: !include deps/panel_iframe.yaml
# Device tracker configuration
device_tracker: !include deps/device_tracker.yaml
# API to offer information on the system and its components
system_health:
# The person component allows to connect device tracker entities to one or more person entities
person: !include deps/person.yaml
zigbee2mqtt_networkmap:
